routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware'	=>	'auth', ], function(){

    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/done', 'HomeController');
    Route::resource('/tasks', 'TasksController');
    Route::resource('/lists', 'ListsController');
});

Route::group(['middleware'	=>	'auth', 'namespace'=>'Auth'], function(){

    Route::get('/logout', 'AuthController@logout')->name('logout');

});

Route::group(['middleware'	=>	'guest', 'namespace'=>'Auth'], function(){

    Route::get('/register', 'AuthController@registerForm')->name('registerForm');
    Route::post('/register', 'AuthController@register')->name('register');

    Route::get('/verify/{token}', 'ConfirmationEmailController@confirm')->name('email.confirmation');

    Route::get('/email', 'ResetPassController@emailResetPass')->name('email.resetPassForm');
    Route::post('/email', 'ResetPassController@sendResetToken')->name('sendResetToken');

    Route::get('/resetPass/{token}/edit', 'ResetPassController@resetPassForm')->name('resetPassForm');
    Route::put('/resetPass/{token}', 'ResetPassController@resetPass')->name('resetPass');

    Route::group(['middleware'	=>	'checkstatus'], function(){

        Route::get('/login', 'AuthController@loginForm')->name('loginForm');
        Route::post('/login', 'AuthController@login')->name('login');

    });

});

Route::group(['middleware'	=>	'admin', 'namespace'=>'Admin'], function(){

    Route::get('/admin', 'AdminController@index')->name('admin');
    Route::get('/userList', 'AdminController@usersList')->name('users.list');
    Route::put('/set_admin/{id}', 'AdminController@setAdmin');
    Route::put('/activate/{id}', 'AdminController@setStatus');

});

resources/views/head.blade.php
<head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>My ToDo list</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{route('home')}}">To-Do</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

            @if (Auth::check())
                <li class="nav-item">
                    <a class="nav-link" href="{{route('logout')}}">Logout</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{route('home')}}">{{Auth::user()->name}}</a>
                </li>

            @else

                <li class="nav-item">
                    <a class="nav-link" href="{{route('loginForm')}}">Login</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{route('registerForm')}}">Register</a>
                </li>
            @endif

                @if (Auth::check() && Auth::user()->is_admin)
            <li class="nav-item">
                <a class="nav-link" href="{{route('admin')}}">All Lists</a>
            </li>

            <li class="nav-item ">
                <a class="nav-link" href="{{route('users.list')}}">Users list</a>
            </li>
                @endif

        </ul>

    </div>
</nav>

resources/views/index.blade.php
@extends('layout')

@section('content')
<div class="container">

    <h1>To-do</h1>

    @if(!empty($lists))

    <ul class="list-group">

        @foreach($lists as $list)


        <li class="list-group-item">{{$list->title}}
            <div class="btn-group pull-right">
                <a href="{{route('lists.edit', $list->id)}}" class="btn btn-outline-info">Edit</a>

                {{Form::open(['route'=>['lists.destroy', $list->id], 'method'=>'delete'])}}
                <button onclick="return confirm('are you sure?')" type="submit" class="btn btn-danger">Delete</button>
                {{Form::close()}}
            </div>
        </li>

            @foreach($list->getTask() as $task)

                <li class="list-group-item @if($task->done)  list-group-item-success @else list-group-item-primary @endif"> {{$task->name}}

                    <div class="btn-group pull-right">

                        {{Form::open(['action'=>['HomeController@update', $task->id], 'method'=>'put'])}}
                        <button onclick="" type="submit" class="btn btn-outline-success ">Mark</button>
                        {{Form::close()}}

                        <a href="{{route('tasks.edit', $task->id)}}" class="btn btn-outline-info ">Edit</a>

                        {{Form::open(['route'=>['tasks.destroy', $task->id], 'method'=>'delete'])}}
                        <button onclick="return confirm('are you sure?')" type="submit" class="btn btn-danger ">Delete</button>
                        {{Form::close()}}

                    </div>
                </li>
            @endforeach

            @include('tasks.create')

         @endforeach

    </ul>

@else

    <h1>Нет заданий</h1>

    @endif

    <a href="{{route('lists.create')}}" class="btn btn-success btn-lg btn-block">Создать новый списк</a>

</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>

@include('head')

@include('errors.errors')

@if(session('verify'))
    <div class="alert alert-danger">
        {{session('verify')}}
    </div>
@endif
@if(session('verifyOk'))
    <div class="alert alert-primary">
        {{session('verifyOk')}}
    </div>
@endif

<body>

<div class="container">

    <div class="starter-template">

        @yield('content')

    </div>

</div>

</body>

</html>